server:
  port: 8083

# hystrix设置
hystrix:
  threadpool:
    default:
      coreSize: 5
      maxQueueSize: 20
      queueSizeRejectionThreshold: 20
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 1800000
management:
  endpoints:
    web:
      exposure:
        include: "*"
