spring:
  application:
    name: base-mybatis-generator
  datasource:
    username: root
    password: Huabin123$
    url: jdbc:mysql://localhost:3306/sqlinproject
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8012
